apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: jvm-build-suite-component-putx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jvm-build-suite-component-putx
    app.kubernetes.io/part-of: jvm-build-suite-application-qcgv
  name: jvm-build-suite-component-putx
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: jvm-build-suite-component-putx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: jvm-build-suite-component-putx
    spec:
      containers:
      - image: quay.io/rycole-appstudio/jvm-build-erru-tenant/jvm-build-suite-application-qcgv/jvm-build-suite-component-putx@sha256:2377283aaedb623e521ec21ab9ef7abbed6516c99404809d43a920a5213f02b9
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
